---
title: "lab2"
format: html
editor: visual
---

```{r}
#1
glimpse(tree_dat)

# answer: there are 131,386 rows and 8 columns. The columns are tree ID, stand ID, stand, year, species, age, inc (linear growth increment), and rad_ib (bark radius of tree at breast height).
```

```{r}
#2
tree_count1 <- tree_dat %>%
  filter(standID == 1)
print(tree_count1)

# answer: 979
```

```{r}
#3
tree_dat %>%
  filter(species %in% c("ABBA", "PIST")) %>%
  count(species)

# answer: ABBA - 13033; PIST - 4188
```

```{r}
#4
tree_dat %>%
  filter(year == max(year), age > 200) %>%
  tally()

# answer: 7
```

```{r}
#5
tree_dat %>%
  slice_max(age)

# answer: 269
```

```{r}
#6
tree_dat %>%
  filter(year == 2001) %>%
  slice_max(age, n = 5)

# answer: 263, 259, 212, 206, 206
```

```{r}
#7
tree_dat %>%
  slice_sample(prop = 0.3) %>%
  tally()

# answer: 39415
```

```{r}
#8
tree_dat %>%
  filter(standID == 5, year == 2007) %>%
  arrange(desc(rad_ib)) %>%
  slice_head(n = 3)

# answer: 128, 157, 135
```

```{r}
#9
tree_dat %>%
  select(treeID, standID, year, rad_ib) %>%
  filter (standID == 3, year == 2007) %>%
  slice_min(rad_ib, n = 3)

# answer: 50, 56, 36
```

```{r}
#10
tree_dat %>%
  select(treeID, standID, year, rad_ib) %>%
  select(-standID) %>%
  glimpse()

# answer: table
```

```{r}
#11
tree_dat %>%
  select(contains("ID")) %>%
  glimpse()

# answer: table
```

```{r}
#12
tree_dat %>%
  select(contains("ID") | contains("stand")) %>%
  glimpse()

# answer: table
```

```{r}
#13
tree_dat <- tree_dat %>%
  rename(rad_ib_mm = rad_ib, inc_mm = inc) %>%
  glimpse ()

#answer: table
```

```{r}
#14
tree_dat %>%
  mutate(DBH = rad_ib_mm/10) %>%
  mutate(BA_m2 = 0.00007854*DBH^2) %>%
  filter(species == "POTR", year == 2007) %>%
  summarise(mean_BA_m2 = mean(BA_m2, na.rm = TRUE))

# answer: 0.009241546
```

```{r}
#15
tree_dat %>%
  mutate(established = if_else(age > 5, TRUE, FALSE)) %>%
  count(established)

# answer: TRUE - 122503; FALSE - 8883
```

```{r}
#16
tree_dat %>%
  mutate(DBH_class = case_when(DBH >= 0 & DBH < 2.5 ~ "seedling", DBH >= 2.5 & DBH < 10 ~ "sapling", DBH >= 10 & DBH < 30 ~ "pole", DBH >= 30 ~ "sawlog", TRUE ~ NA_character_)) %>%
  filter(year == 2007) %>%
  count(DBH_class)

# answer: pole - 473; sapling - 1817; sawlog - 1
```

```{r}
#17
tree_dat %>%
  filter (year == 2007) %>%
  summarise(mean(DBH), sd(DBH))

# answer: mean - 8.046755, this is the average DBH of all trees in the data set; sd - 3.069321, this is shows how spread out the tree DBH is compared to the mean DBH.
```

```{r}
#18
tree_dat %>%
  filter(year == 2003) %>%
  group_by(species) %>%
  summarise(mean_age = mean(age, na.rm = TRUE)) %>%
  arrange(desc(mean_age)) %>%
  head(3)

# answer: THOC, FRNI, PIST
```

```{r}
#19
tree_dat %>%
  summarise(unique_years = n_distinct(year), first_year = min(year), last_year = max(year))

# answer: unique years - 111; first year - 1897; last year - 2007
```

```{r}
#20
stand_years_sum <- tree_dat %>%
  group_by(standID) %>%
  summarise(unique_years = n_distinct(year)) %>%
  arrange(desc(unique_years))
max_unique_years <- max(stand_years_sum$unique_years)
largest_years <- stand_years_sum %>%
  filter(unique_years == max_unique_years)
largest_years

#answer: stands 1, 15, 16, 17, 24
```

```{r}
# final question

```
